name: OfflineTeleportHere
version: '${project.version}'
main: net.daechler.offlineteleporthere.OfflineTeleportHere
api-version: 1.19
authors: [ Daechler ]
description: Teleport a specific player to a specific location after joining.
commands:
  offlineteleporthere:
    description: Teleport a specific player to a specific location after joining.
    usage: /offlineteleporthere
    permission: offlineteleporthere.use
    aliases: [otph, otphere]